# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 17) do

  create_table "cached_communities", :force => true do |t|
    t.column "name",                :string
    t.column "community_id",        :integer
    t.column "preferred_parent_id", :integer
    t.column "active",              :boolean, :default => true
  end

  create_table "cached_populace_communities", :force => true do |t|
    t.column "community_id", :integer
    t.column "population",   :integer
    t.column "active",       :boolean, :default => true
  end

  create_table "colleges", :force => true do |t|
    t.column "name",   :string
    t.column "active", :boolean, :default => false
  end

  create_table "communities", :force => true do |t|
    t.column "name",              :string
    t.column "created_at",        :datetime
    t.column "updated_at",        :datetime
    t.column "expires_at",        :datetime
    t.column "hashed_name",       :string
    t.column "regex_email",       :string
    t.column "community_type_id", :integer
    t.column "parent",            :integer
    t.column "active",            :boolean,  :default => true
  end

  create_table "community_assigns", :force => true do |t|
    t.column "user_id",      :integer
    t.column "community_id", :integer
    t.column "active",       :boolean, :default => true
  end

  create_table "community_tags", :force => true do |t|
    t.column "tagname",      :string
    t.column "community_id", :integer
    t.column "created_at",   :datetime
    t.column "active",       :boolean,  :default => true
  end

  create_table "community_types", :force => true do |t|
    t.column "name", :string
  end

  create_table "email_invites", :force => true do |t|
    t.column "email",      :string
    t.column "user_id",    :integer
    t.column "invite_id",  :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "active",     :boolean,  :default => true
  end

  create_table "invited_users", :force => true do |t|
    t.column "invite_id",  :integer
    t.column "user_id",    :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "active",     :boolean,  :default => true
    t.column "confirmed",  :boolean,  :default => false
  end

  create_table "invites", :force => true do |t|
    t.column "content",             :text
    t.column "user_id",             :integer
    t.column "maximum_users",       :integer
    t.column "expiration_interval", :integer
    t.column "expires_at",          :datetime
    t.column "created_at",          :datetime
    t.column "updated_at",          :datetime
    t.column "active",              :boolean,  :default => true
  end

  create_table "photos", :force => true do |t|
    t.column "image",      :string
    t.column "user_id",    :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "sexes", :force => true do |t|
    t.column "name", :string
  end

  create_table "user_assigns", :force => true do |t|
    t.column "user_alpha_id", :integer
    t.column "user_beta_id",  :integer
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
    t.column "active",        :boolean,  :default => true
  end

  create_table "user_preferences", :force => true do |t|
    t.column "user_id",    :integer
    t.column "invite_in",  :boolean,  :default => true
    t.column "times_up",   :boolean,  :default => true
    t.column "afirm_out",  :boolean,  :default => true
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "user_types", :force => true do |t|
    t.column "name", :string
  end

  create_table "users", :force => true do |t|
    t.column "first_name",      :string
    t.column "last_name",       :string
    t.column "email",           :string
    t.column "yotag_id",        :integer
    t.column "user_type_id",    :integer
    t.column "phone",           :string
    t.column "sex_id",          :integer
    t.column "interest_1",      :string
    t.column "interest_2",      :string
    t.column "interest_3",      :string
    t.column "college_id",      :integer
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "hashed_password", :string
    t.column "salt",            :string
    t.column "terms",           :boolean,  :default => false
    t.column "active",          :boolean,  :default => true
  end

  create_table "yotags", :force => true do |t|
    t.column "tag",        :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "active",     :boolean,  :default => true
  end

end
