# MySQL (default setup).  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql
# On MacOS X:
#   gem install mysql -- --include=/usr/local/lib
# On Windows:
#   gem install mysql
#       Choose the win32 build.
#       Install MySQL and put its /bin directory on your path.
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
chrisdev:
  adapter: mysql
  database: yywt_chrisdev
  username: changeme
  password: changeme
  socket: /var/run/mysqld/mysqld.sock
macbook:
  adapter: mysql
  database: yywt_macbook
  username: root
  password: thx1138
  socket: /opt/local/var/run/mysql5/mysqld.sock 
development:
  adapter: mysql
  database: yoyouwa_development
  username: root
  password: root
 
test:
  adapter: mysql
  database: yywt_test
  username: root
  password: thx1138
  socket: /opt/local/var/run/mysql5/mysqld.sock 
staging:
  adapter: mysql
  database: yoyouwa_staging
  username: yoyouwa_root
  password: thx1138
  socket: /tmp/mysql.sock
production:
  adapter: mysql
  database: production
  username: yywt
  password: thx1138
  socket: /var/lib/mysql/mysql.sock
